@extends('layouts.secretary-master')

@section('content')
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!--   <div class="row">
    <div class="center col l12 m12 s12">
      <h3>Job Order</h3>
    </div>
  </div>
 -->

<div class="row page-title">
  <div class="col s12 m12 l12">
    <h5>Job Order</h5>
  </div>
</div>


<div class="main-wrapper">
  <!-- ACTUAL PAGE CONTENT GOES HERE -->
  <form action="{{ URL::to('/sec-joborder-add') }}" method="POST" id="signup_validate" enctype="multipart/form-data">
       <div class="row">
            <div class="input-field col s12 m4 l4">
              <!-- dapat autogenerated-->
              <input type="text" name="transaction-no" required="" value="{{$data->strJOName}}">
              <label for="transaction-no">Transaction No.</label>
            </div>
      </div>

      <div class="card">
        <div class="card-content">
            <div class="row">
              <div class="col l12 m6 s6">
                  <div class="row">
                      <div class="col s12">

                              <p>
                                  <input type="checkbox" class="filled-in" id="eyeglass" name="eyeglass" value='eyeglass' @if(strpos($data->strJODetails , '1') != false) checked @endif/>
                                  <label for="eyeglass" class="black-text bold">EYE GLASS</label>
                              </p>
                              <p>
                                  <input type="radio" name="group1" id="single" name="single" value='single' @if(strpos($data->strJODetails , '2') != false) checked @endif>
                                  <label for="single" class="light-blue-text text-darken-4 bold">SINGLE</label>
                              </p>
                              <div id="divSingle" class="row">
                                <div class="col l4 s12">
                                  <p style="text-indent: 20px">
                                    <input type="checkbox" id="lhi" @if(strpos($data->strJODetails , '3') != false) checked @endif>
                                    <label for="lhi">LHI MULTI</label>
                                  </p>
                                  <p style="text-indent: 20px">
                                      <input type="checkbox" id="multi"  @if(strpos($data->strJODetails , '4') != false) checked @endif>
                                      <label for="multi">MULTI</label>
                                  </p>
                                </div>
                                <div class="col l4 s12">
                                  <p style="text-indent: 20px">
                                    <input type="checkbox" id="hc" @if(strpos($data->strJODetails , '5') != false) checked @endif>
                                    <label for="hc">H.C.</label>
                                  </p>
                                  <p style="text-indent: 20px">
                                      <input type="checkbox" id="cr39" @if(strpos($data->strJODetails , '6') != false) checked @endif>
                                      <label for="cr39">CR39</label>
                                  </p>
                                </div>
                                <div class="col l4 s12"></div>
                              </div>

                      </div>
                      <div class="col s12">

                              <p style="">
                                  <input type="radio"  name="group1" id="double" @if(strpos($data->strJODetails , '7') != false) checked @endif>
                                  <label for="double" class="light-blue-text text-darken-4 bold">DOUBLE</label>
                              </p>
                              <div id="divDouble">
                                <div class="row">
                                  <div class="col l4 s12">
                                    <p style="text-indent: 20px">
                                      <input type="checkbox" id="kk" @if(strpos($data->strJODetails , '8') != false) checked @endif>
                                      <label for="kk">KK</label>
                                    </p>
                                    <p style="text-indent: 20px">
                                        <input type="checkbox" id="flattop" @if(strpos($data->strJODetails , '9') != false) checked @endif>
                                        <label for="flattop">FLAT TOP</label>
                                    </p>
                                    <p style="text-indent: 20px">
                                        <input type="checkbox" id="progressive" @if(strpos($data->strJODetails , 'a') != false) checked @endif>
                                        <label for="progressive">PROGRESSIVE</label>
                                    </p>
                                  </div>
                                  <div class="col l4 s12">
                                      <p style="text-indent: 20px">
                                          <input type="checkbox" id="exec" @if(strpos($data->strJODetails , 'b') != false) checked @endif>
                                          <label for="exec">EXEC</label>
                                      </p>
                                      <p style="text-indent: 20px">
                                          <input type="checkbox" id="noline" @if(strpos($data->strJODetails , 'c') != false) checked @endif>
                                          <label for="noline">NOLINE</label>
                                      </p>
                                  </div>
                                  <div class="col l4 s12"></div>
                                </div>
                                <div class="row">
                                  <div class="col l4 s12">
                                     <p style="text-indent: 20px; margin-left: 30px">
                                        <input type="checkbox" id="hoyanm" @if(strpos($data->strJODetails , 'd') != false) checked @endif>
                                        <label for="hoyanm">HOYA NM</label>
                                      </p>
                                  </div>
                                  <div class="col l4 s12">
                                    <p style="text-indent: 20px">
                                        <input type="checkbox" id="vrx" @if(strpos($data->strJODetails , 'e') != false) checked @endif>
                                        <label for="vrx">VRX</label>
                                    </p>
                                  </div>
                                  <div class="col l4 s12"></div>
                                  
                                </div>
                                
                                <div class="row">
                                  <div class="col l4 s12">
                                    <p style="text-indent: 20px">
                                        <input type="checkbox" id="hoyamlti" @if(strpos($data->strJODetails , 'f') != false) checked @endif>
                                        <label for="hoyamlti">HOYA MLTI</label>
                                    </p>
                                  </div>
                                  <div class="col l4 s12">
                                    <p style="text-indent: 20px">
                                        <input type="checkbox" id="pentax" @if(strpos($data->strJODetails , 'g') != false) checked @endif>
                                        <label for="pentax">PENTAX</label>
                                    </p>
                                  </div>
                                  <div class="col l4 s12"></div>
                                </div>
                              </div>

                      </div>
                  </div>
                  <div class="row">
                      <div class="col s12 m6 l4">

                              <p>
                                  <input type="checkbox" class="filled-in" id="glass" @if(strpos($data->strJODetails , 'h') != false) checked @endif/>
                                  <label for="glass" class="black-text bold">GLASS</label>
                              </p>
                              <p>
                                  <input type="checkbox" class="filled-in" id="plastic" @if(strpos($data->strJODetails , 'i') != false) checked @endif/>
                                  <label for="plastic" class="black-text bold">PLASTIC</label>
                              </p>

                      </div>
                    
                  </div>
              </div>
            </div>
        </div>
      </div>
      <hr>
      
      <div class="card">
          <div class="card-content">
              <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Sph. Cyl*</th>
                      <th>Axiz*</th>
                      <th>B.C.*</th>
                      <th>P.D.*</th>
                    </tr>
                  </thead>
                  <tbody>
                      <tr>
                        <td>O.D.</td>
                        <td><input type="text" name="odsc" id="odsc" value="{{$data->strJOODSC}}"></td>
                        <td><input type="text" name="odax" id="odax" value="{{$data->strJOODA}}"></td>
                        <td><input type="text" name="odbc" id="odbc" value="{{$data->strJOODBC}}"></td>
                        <td><input type="text" name="odpd" id="odpd" value="{{$data->strJOODPD}}"></td>
                      </tr>
                      <tr>
                        <td>O.S.</td>
                        <td><input type="text" name="ossc" id="ossc" value="{{$data->strJOOSSC}}"></td>
                        <td><input type="text" name="osax" id="osax" value="{{$data->strJOOSA}}"></td>
                        <td><input type="text" name="osbc" id="osbc" value="{{$data->strJOOSBC}}"></td>
                        <td><input type="text" name="ospd" id="ospd" value="{{$data->strJOOSPD}}"></td>
                      </tr>
                  </tbody>
              </table>
              <div class="row">
                <div class="col l4">
                Frame:<input type="text" name="addod" id="addod" value="{{$data->strItemName}} - {{$data->strItemDesc}} ">
                Lens:<input type="text" name="addos" id="addos" value="{{$data->strItemName}} - {{$data->strItemDesc}}">
                </div>

                <div class="col l4">
                Add OD*:<input type="text" name="addod" id="addod" value="{{$data->intJOAOD}}">
                Add OS*:<input type="text" name="addos" id="addos" value="{{$data->intJOAOS}}">
                </div>
              </div>
             
          </div>  
      </div>
      <hr>
      <div class="card">
        <div class="card-content">
          <div class="row">
                <div class="col l6 m6 s12">
                    <div class="row">
                      <div class="input-field">
                        <label for="note">Note:</label>
                        <input id="note" name="note" type="text" value="" />
                      </div>
                    </div>
                    <div class="row">
                      <div class="input-field">
                        <label for="doctor">Doctor-in-Charge:</label>
                        <input id="doctor" name="doctor" type="text" value="" />
                      </div>
                    </div>
                    <div class="row">
                      <div class="input-field">
                        <label for="sales">Sales-in-Charge:</label>
                        <input id="sales" name="sales" type="text" value="{{Session::get('user_name')}}" />
                      </div>
                    </div>
                </div>
                <div class="col s12 m6 l6">
                    <div class="row">
                      <div class="input-field"> 
                        <label for="amount" name="amount" id="amount">Amount*:</label>
                        <input type="number" name="amount" id="amount" value="$data[0]->dcJOFee">
                      </div>
                    </div>
                    <div class="row">
                      <div class="input-field">
                        <label for="deposit">Deposit:</label>
                        <input type="number" name="deposit" id="deposit">
                      </div>
                    </div>
                    <div class="row">
                      <div class="input-field">
                        <label for="balance">Balance:</label>
                        <input type="number" name="balance" id="balance" disabled="disable">
                      </div>
                    </div>
                </div>
          </div>

        </div>
      </div>

  </form>
</div>


{{-- Scripts START --}}
<script src="js/jquery-1.11.1.min.js"></script>
<script src="js/jquery.validate.min.js"></script>
<script type="text/javascript">
    $().ready(function() {
    $("#signup_validate").validate({
      rules: {
        odsc: "required",
        odax: "required",
        odbc: "required",
        odpd: "required",
        ossc: "required",
        osax: "required",
        osbc: "required",
        ospd: "required",
        frames: "required",
        lens: "required",
        addod: "required",
        addos: "required",
        // patient: "required",
        amount: "required",
      },
      errorElement: 'div'
    });
  });


  $(document).ready(function() {

    $("#divSingle").hide();
    $("#divDouble").hide();
    $("input[name$='group1']").click(function() {
        var radio = $(this).attr('id');
        if(radio == "single"){
          $("#divSingle").show();
          $("#divDouble").hide();
          $('#lhi, #multi, #hc, #cr39').attr('checked', false);
        }else{
          $("#divSingle").hide();
          $("#divDouble").show();
          $('#kk, #flattop, #progressive, #exec, #noline, #hoyanm, #hoyamlti, #vrx, #pentax ').attr('checked', false);
        }
    });
});

</script>
{{-- Scripts END --}}
@endsection